function imu_data = import_imu_data(filename)
% IMPORT_IMU_DATA Import IMU data from ESP32 CSV file
%
% Syntax:
%   imu_data = import_imu_data('run001.csv')
%
% Description:
%   Reads CSV file generated by ESP32 MPU9250 data logger and returns
%   a structure containing time-series data for vehicle dynamics analysis.
%
% Input:
%   filename - Path to CSV file from ESP32 data logger
%
% Output:
%   imu_data - Structure containing:
%       .time      - Time vector (seconds)
%       .ax        - Longitudinal acceleration (m/s^2)
%       .ay        - Lateral acceleration (m/s^2)
%       .az        - Vertical acceleration (m/s^2)
%       .gx        - Roll rate (rad/s)
%       .gy        - Pitch rate (rad/s)
%       .gz        - Yaw rate (rad/s)
%       .ax_g      - Longitudinal acceleration (g)
%       .ay_g      - Lateral acceleration (g)
%       .az_g      - Vertical acceleration (g)
%       .sample_rate - Actual sample rate (Hz)
%       .duration  - Total recording duration (s)
%       .filename  - Source filename
%
% Example:
%   imu = import_imu_data('run001.csv');
%   plot(imu.time, imu.ay_g);
%   xlabel('Time (s)');
%   ylabel('Lateral Acceleration (g)');
%
% Author: Team Unwired
% Date: January 2026

% Constants
G = 9.81;  % m/s^2

% Read CSV file
fprintf('Reading %s... ', filename);
data = readtable(filename);
fprintf('OK (%d samples)\n', height(data));

% Extract columns
imu_data.time = data.time_s;
imu_data.ax_g = data.ax_g;
imu_data.ay_g = data.ay_g;
imu_data.az_g = data.az_g;

% Convert to SI units
imu_data.ax = data.ax_g * G;           % m/s^2
imu_data.ay = data.ay_g * G;           % m/s^2
imu_data.az = data.az_g * G;           % m/s^2
imu_data.gx = data.gx_dps * pi / 180;  % rad/s
imu_data.gy = data.gy_dps * pi / 180;  % rad/s
imu_data.gz = data.gz_dps * pi / 180;  % rad/s

% Store raw gyro values as well
imu_data.gx_dps = data.gx_dps;
imu_data.gy_dps = data.gy_dps;
imu_data.gz_dps = data.gz_dps;

% Calculate metadata
imu_data.duration = imu_data.time(end) - imu_data.time(1);
imu_data.sample_rate = (length(imu_data.time) - 1) / imu_data.duration;
imu_data.filename = filename;

% Print summary
fprintf('Duration: %.2f seconds\n', imu_data.duration);
fprintf('Sample rate: %.1f Hz\n', imu_data.sample_rate);
fprintf('Max lateral acceleration: %.2f g\n', max(abs(imu_data.ay_g)));
fprintf('Max longitudinal acceleration: %.2f g\n', max(abs(imu_data.ax_g)));
fprintf('Max yaw rate: %.1f deg/s\n', max(abs(imu_data.gz_dps)));

end
